### ISSUE TITLE
read papers

### ISSUE THREAD

**Issue by jiunbae** [MaybeS/MOT#17]
append list

**Comment by jiunbae** [comment]
- [ ] Online Parameter Tuning for Object Tracking Algorithms

**Comment by jiunbae** [comment]
- [ ] CREST: Convolutional Residual Learning for Visual Tracking
- [x] Tracking as Online Decision-Making: Learning a Policy from Streaming Videos with Reinforcement Learning
- [ ] ECO: Efficient Convolution Operators for Tracking
- [ ] STCT: Sequentially Training Convolutional Networks for Visual Tracking
- [x] Learning to Track: Online Multi-object Tracking by Decision Making

**Comment by jkjh0819** [comment]
CREST: https://github.com/ybsong00/CREST-Release (matlab)
ECO: https://github.com/martin-danelljan/ECO (matlab)
Learning to Track: https://github.com/yuxng/MDP_Tracking (matlab)

in summarizing CREST

**Comment by jiunbae** [comment]
- [x] High-Speed Tracking-by-Detection Without Using Image Information

**Comment by jiunbae** [comment]
Maybe, we can make python version of [MDP tracking](https://github.com/yuxng/MDP_Tracking).

**Comment by jiunbae** [comment]
maybe enough
